---
title: "ADA MID"
author: "yoseph"
date: "10/15/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

a) importing the dataset
```{r}
library(haven)
library(readr)
library(dplyr)
df = read.csv('https://github.com/kijohnson/Data/blob/main/titanic.csv?raw=true')
```

b) determining the median age for by passenger class
```{r}
df %>%
    group_by(Pclass) %>%
    dplyr::summarize(median_age = median(Age, na.rm=TRUE))


```
interpretation of the median 
The midian age for

c) a plot that shows medians, spread of data, and outliers for the continuous variable age according to passenger class
```{r}
library (tidyverse)
ggplot(data = df) + 
  stat_summary(
    mapping = aes(x = Pclass, y = Age),
    fun.min = min,
    fun.max = max,
    fun = median)

```


```{r}
ggplot(data=df)+
  geom_point(aes(x=Pclass, y= Age))+
  stat_summary(mapping = aes(x = Pclass, y = Age),
    fun = median, geom = "crossbar", width = 0.2)

```


```{r}
ggplot(df, aes(x = factor(Pclass), y = Age, fill = factor(Pclass))) + 
  geom_boxplot() + 
  stat_summary(
    aes(label = round(stat(y), 1)),
    geom = "text", 
    fun.y = function(y) { o <- boxplot.stats(y)$out; if(length(o) == 0) NA else o },
    hjust = -2
  )
outliers = boxplot(df$Age, plot=FALSE)$out
outliers
```


```{r}
